// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.LoanCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("loanAmount")]
        public long LoanAmount { get; set; }

        [JsonProperty("downpayment")]
        public long Downpayment { get; set; }

        [JsonProperty("interestRate")]
        public double InterestRate { get; set; }

        [JsonProperty("loanTerm")]
        public long LoanTerm { get; set; }

        [JsonProperty("monthly_payment")]
        public double MonthlyPayment { get; set; }

        [JsonProperty("total_interest_paid")]
        public double TotalInterestPaid { get; set; }

        [JsonProperty("amortization_schedule")]
        public AmortizationSchedule[] AmortizationSchedule { get; set; }
    }

    public partial class AmortizationSchedule
    {
        [JsonProperty("month")]
        public long Month { get; set; }

        [JsonProperty("interest_payment")]
        public double InterestPayment { get; set; }

        [JsonProperty("principal_payment")]
        public double PrincipalPayment { get; set; }

        [JsonProperty("remaining_balance")]
        public double RemainingBalance { get; set; }
    }
}
